### ISSUE TITLE
reopen issue 76 with a reproducer (ConnectionResetError when writing HDFS)

### ISSUE THREAD

**Issue by mohzhang** [mtth/hdfs#77] opened 2017-07-10 18:22 UTC
[#76](https://github.com/mtth/hdfs/issues/76)

import pickle
from hdfs import Config

DATA_SIZE = 200 * (1 << 20)
data = 'a' * DATA_SIZE

hclient = Config('./hdfscli.cfg').get_client()
with hclient.write('/tmp/test.tmp', overwrite=True) as writer:
    writer.write(pickle.dumps(data))

**Comment by mtth** [comment] 2017-07-16 17:21
Can't reproduce it here even with larger sizes, `hdfs` also already [streams](http://docs.python-requests.org/en/master/user/advanced/#chunk-encoded-requests) uploads which usually helps. It looks like it's an issue with the connection to your cluster. Does it work if you [upload the file manually](https://hadoop.apache.org/docs/r1.0.4/webhdfs.html#CREATE)?

**Comment by mohzhang** [comment] 2017-07-17 12:51
I found following code works:

import pickle
from hdfs import Config

DATA_SIZE = 200 * (1 << 20)
data = 'a' * DATA_SIZE

hclient = Config('./hdfscli.cfg').get_client()
hclient.write('/tmp/test.tmp', pickle.dumps(data), overwrite=True)

My guess is this just has one write. But the old code may have multiple writes and connection is closed after first write.

**Comment by mtth** [comment] 2017-09-08 04:03
Closing as I'm unable to reproduce this locally and investigate further.

**Closed by mtth** 2017-09-08 04:03 UTC
