### ISSUE TITLE
readlines() is extremely slow

### ISSUE THREAD

**Issue by Khris777** [mtth/hdfs#54] opened 2016-09-16 09:44 UTC
I'm reading in a 2.67 MB json file from a hdfs filesystem. It has 2809922 characters in 254 lines.

    from hdfs import InsecureClient
    client = InsecureClient(hadoopDirectory, user=me)

Following the quickstart guide and using `timeit` I measured this bit of code:

    with client.read(filename) as reader:
      output = reader.read()

The `read()` method takes `59.2 ms`.

However just substituting `read()` with `readlines()` increases the time to `1 min 3 s` which is a more than thousand-fold increase for the same file.

Reading only the first line with `readline()` is also slow, it already takes `991 ms`, though the lines are unevenly long.

Reading the file locally with standard python like this

    with open(filename) as reader:
      output = reader.readlines()

takes `8.46 ms`.

**Comment by mtth** [comment] 2016-09-17 18:41
That's odd.

+ What version of python, HdfsCLI, and `requests` are you using?

+ Can you try iterating over the reader directly and timing the outcome:

  ```python
  with client.read(filename, encoding='utf-8', delimiter='\n') as reader:
    lines = [line for line in reader]
  ```

+ Can you set `requests`' and `hdfs`' log level to `DEBUG` and share the logs here?

+ Why are you calling `readlines` to read a single JSON object?

**Comment by Khris777** [comment] 2016-09-19 06:57
1. Versions:

- Python version: 2.7.12

- HdsfCLI version: 2.0.11
- I'm not using requests (should I?).

2. The outcome is `460 ms per loop`, around ten times slower than `read()`. The `read()` method is faster today, with around 38 ms instead of 59, likely due to less general system usage here. Using the `readlines()` method is still very slow and just got me kicked out of the network. I'm using a virtual machine on my company's main frame if that helps in any way.

3. Not sure how to do that, I tried `config.Config(stream_log_level = "DEBUG")`, but I'm not seeing any output in the console. Is it in a stored in a file? Sorry, I'm a beginner with using your module.

4. I wasn't being clear, sorry. It'a multi-JSON file, each line is a JSON object, so using `readlines()` makes sense. I can as well use `read()` and then do `split('\n')` to get the desired output, so I can circumvent the problem easily. I still wanted to report it since something is clearly wrong somewhere.

**Comment by mtth** [comment] 2016-09-25 17:59
Thanks!

> Not sure how to do that, I tried config.Config(stream_log_level = "DEBUG"), but I'm not seeing any output in the console. Is it in a stored in a file? Sorry, I'm a beginner with using your module.

By default the logs are written to a temporary file. You can view its path by running `hdfscli -L`.

> I wasn't being clear, sorry. It'a multi-JSON file, each line is a JSON object, so using readlines() makes sense. I can as well use read() and then do split('\n') to get the desired output, so I can circumvent the problem easily. I still wanted to report it since something is clearly wrong somewhere.

No worries, thanks for reporting this. It's definitely unexpected behavior. I was able to reproduce it and the slowness seems to come from `requests`' streaming response objects. The following snippet reproduces the behavior:

```python
import requests

response = requests.get(HTTP_URL_TO_LARGE_FILE, stream=True) # Streaming HTTP request.
stream = response.raw # File-like object (similar to what `client.read` returns).
lines = stream.readlines() # Very slow.
```

I'm not sure yet why this is the case but it doesn't seem to be specific to `hdfs`. For your particular use-case (decoding JSON lines), I'd recommend specifying an encoding to `client.read` over using the `reader.read().split('\n')` idiom. `readlines` should then be almost as fast as `read` (since it actually [delegates to that method](https://github.com/python/cpython/blob/f18a11b6340b0413ca85b034efbbe1f55753303f/Lib/codecs.py#L615)):

```python
with client.read(filename, encoding='utf-8') as reader:
  lines = reader.readlines()
```

Specifying an encoding here is good practice since JSON is a text-based encoding (in python 3, the parser will even fail when passed a binary string). Iterating over the reader directly is slower (as you've confirmed) because reads are buffered and the buffer sizes are small compared to the size of each line here.

I updated [`client.read`](https://hdfscli.readthedocs.io/en/latest/api.html#hdfs.client.Client.read)'s documentation with a warning on performance. I'll close this issue since it doesn't seem like there is much that can be done from `hdfs` other than the workarounds we've already identified. I'd be curious to know more about the underlying cause though.

**Closed by mtth** 2016-09-25 17:59 UTC

**Comment by Khris777** [comment] 2016-09-26 07:46
Thank you for the explanation and the workaround.

Using

    with client.read(filename, encoding='utf-8') as reader:
       lines = reader.readlines()

gives me a performance of `54.4 ms` compared to `1min 3s` without the `enconding` tag.

It's even faster than using `reader.read()` which needs `74.8 ms`.
