### ISSUE TITLE
/usr/bin/hdfs needs rename

### ISSUE THREAD

**Issue by opsmekanix** [mtth/hdfs#10] opened 2015-02-19 18:19 UTC
It would be good to rename /usr/bin/hdfs to something else, for example hdfscli.  The issue is when installing your package on hosts with Hadoop 2 already installed, when people run the hadoop hdfs command, most likely yours will called instead as /usr/bin is typically earlier on $PATH.  

The other issues is if someone like Cloudera, Hortonworks, or Apache Bigtop decides to symlink /usr/bin/hdfs to  the hadoop hdfs command, there will be a package conflict preventing installation.

**Comment by mtth** [comment] 2015-02-20 20:55
I hadn't heard of any conflicting utilities, are you saying that `hadoop fs`  becomes `hdfs` in version 2?

**Comment by opsmekanix** [comment] 2015-02-21 04:54
Correct. The file system commands have been removed from the hadoop command.  For example 'hadoop dfs -ls /' is now 'hdfs dfs -ls /'.  

http://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/HDFSCommands.html

**Comment by mtth** [comment] 2015-02-24 15:52
Ok, I'll have to think about it.

In the meantime, this can be worked around by using aliases (e.g. having something like `hdfscli` aliased to `python -m hdfs`, which clears the conflict). The issue is probably also tempered by the fact that this library is useful for communicating with remote clusters and you _likely_ don't have hadoop installed locally on the same machine.

**Comment by mtth** [comment] 2015-02-24 16:18
Alright, I've pushed a fix in 799250658d811597a853a796a824b93b4a331a45.

Starting from version `0.4.0`, you can configure the entry point used at installation by using the `HDFS_ENTRY_POINT` environment variable. E.g. if you run `HDFS_ENTRY_POINT=hdfscli pip install hdfs`, the entry points will be named `hdfscli` and `hdfscliavro`. The default behavior (i.e. if unspecified) is backwards compatible.

**Closed by mtth** 2015-02-24 16:18 UTC
