### ISSUE TITLE
Upgrading `requests` package breaks hdfs download

### ISSUE THREAD

**Issue by PedroMDuarte** [mtth/hdfs#48] opened 2016-08-10 18:31 UTC
If I do:

```
# pip install hdfs==2.0.9 requests==2.9.1
```

I can successfully run a tests that uploads and downloads a file from HDFS.  Here is a log output of the test:

```
[2016-08-10 18:21:16,054] {client.py:156} INFO - Instantiated <InsecureClient(url='http://cdh:50070')>.
[2016-08-10 18:21:16,055] {client.py:427} INFO - Uploading '/tmp/tmpPQUs8k' to '/tmp/hive_temp_djE7CTrDdAQh995ydwfrcK.csv'.
[2016-08-10 18:21:16,059] {client.py:891} INFO - Listing '/tmp/hive_temp_djE7CTrDdAQh995ydwfrcK.csv'.
[2016-08-10 18:21:16,070] {connectionpool.py:207} INFO - Starting new HTTP connection (1): cdh
[2016-08-10 18:21:16,076] {client.py:375} INFO - Writing to '/tmp/hive_temp_djE7CTrDdAQh995ydwfrcK.csv'.
[2016-08-10 18:21:16,079] {connectionpool.py:207} INFO - Starting new HTTP connection (1): cdh
[2016-08-10 18:21:16,111] {base_hook.py:53} INFO - Using connection to: cdh
[2016-08-10 18:21:16,112] {client.py:156} INFO - Instantiated <InsecureClient(url='http://cdh:50070')>.
[2016-08-10 18:21:16,112] {client.py:650} INFO - Downloading '/tmp/hive_temp_djE7CTrDdAQh995ydwfrcK.csv' to '/tmp/tmp7imrk9out'.
[2016-08-10 18:21:16,114] {client.py:920} INFO - Walking '/tmp/hive_temp_djE7CTrDdAQh995ydwfrcK.csv' (depth 0).
[2016-08-10 18:21:16,119] {client.py:276} INFO - Fetching status for '/tmp/hive_temp_djE7CTrDdAQh995ydwfrcK.csv'.
[2016-08-10 18:21:16,121] {connectionpool.py:207} INFO - Starting new HTTP connection (1): cdh
[2016-08-10 18:21:16,124] {client.py:591} INFO - Reading file '/tmp/hive_temp_djE7CTrDdAQh995ydwfrcK.csv'.
[2016-08-10 18:21:16,128] {connectionpool.py:207} INFO - Starting new HTTP connection (1): cdh
[2016-08-10 18:21:16,137] {base_hook.py:53} INFO - Using connection to: cdh
[2016-08-10 18:21:16,138] {client.py:156} INFO - Instantiated <InsecureClient(url='http://cdh:50070')>.
[2016-08-10 18:21:16,138] {client.py:766} INFO - Deleting '/tmp/hive_temp_djE7CTrDdAQh995ydwfrcK.csv'.
[2016-08-10 18:21:16,139] {connectionpool.py:207} INFO - Starting new HTTP connection (1): cdh
```

If I now upgrade the `requests` package to a later version:

```
pip install hdfs==2.0.9 requests==2.11.0
```

I get the following;

```
[2016-08-10 18:24:45,246] {base_hook.py:53} INFO - Using connection to: cdh
[2016-08-10 18:24:45,247] {client.py:157} INFO - Instantiated <InsecureClient(url='http://cdh:50070')>.
[2016-08-10 18:24:45,248] {client.py:645} INFO - Downloading '/data/barclay/raw_excel/2016-07-10.xlsx' to 'local3.xlsx'.
[2016-08-10 18:24:45,249] {client.py:914} INFO - Walking '/data/barclay/raw_excel/2016-07-10.xlsx' (depth 0).
[2016-08-10 18:24:45,249] {client.py:279} INFO - Fetching status for '/data/barclay/raw_excel/2016-07-10.xlsx'.
[2016-08-10 18:24:45,256] {connectionpool.py:214} INFO - Starting new HTTP connection (1): cdh
[2016-08-10 18:24:45,262] {client.py:586} INFO - Reading file '/data/barclay/raw_excel/2016-07-10.xlsx'.
[2016-08-10 18:24:45,268] {connectionpool.py:214} INFO - Starting new HTTP connection (1): cdh
[2016-08-10 18:25:44,239] {client.py:721} ERROR - Error while downloading. Attempting cleanup.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/hdfs/client.py", line 717, in download
    _download(fpath_tuple)
  File "/usr/local/lib/python2.7/site-packages/hdfs/client.py", line 660, in _download
    for chunk in reader:
  File "/usr/local/lib/python2.7/site-packages/requests/utils.py", line 372, in stream_decode_response_unicode
    raise UnicodeError("Unable to decode contents with encoding %s." % encoding)
UnicodeError: Unable to decode contents with encoding None.
---------------------------------------------------------------------------
UnicodeError                              Traceback (most recent call last)
<ipython-input-3-e7e086a08bcd> in <module>()
----> 1 hook.hdfs_download('/data/barclay/raw_excel/2016-07-10.xlsx', 'local3.xlsx')

/opt/altx_data_pipeline/altx_data_pipeline/utils/air/hooks/hive_hooks.pyc in hdfs_download(self, hdfs_path, local_path, overwrite)
    255     def hdfs_download(self, hdfs_path, local_path, overwrite=False):
    256         hdfs_client = self._get_hdfs_client()
--> 257         hdfs_client.download(hdfs_path, local_path, overwrite=overwrite)
    258 
    259     def table_from_dataframe(self, df, table_name, engine, as_statement=False):

/opt/altx_data_pipeline/altx_data_pipeline/utils/clients/hdfs_client.pyc in download(self, hdfs_path, local_path, overwrite)
     34     def download(self, hdfs_path, local_path, overwrite=False):
     35         c = self.get_conn()
---> 36         c.download(hdfs_path, local_path, overwrite=overwrite)
     37         logger.debug("[HDFS] Downloaded {} to {}".format(hdfs_path,
     38                                                          local_path))

/usr/local/lib/python2.7/site-packages/hdfs/client.pyc in download(self, hdfs_path, local_path, overwrite, n_threads, temp_dir, **kwargs)
    728         _logger.error('Unable to cleanup temporary folder.')
    729       finally:
--> 730         raise err
    731     else:
    732       if temp_path != local_path:

UnicodeError: Unable to decode contents with encoding None.
```

This seems to be a related to an issue in requests version 2.11.0 

kennethreitz/requests#3481

**Comment by mtth** [comment] 2016-08-11 02:02
Nice find, it looks like this is indeed the cause. The change in `requests` has been reverted; are you OK with waiting for it to be released (it looks like it will be in the next few days)?

Otherwise, can you try replacing `True` in [this line](https://github.com/mtth/hdfs/blob/master/hdfs/client.py#L607) (and the one below) to `encoding is not None` and letting me know whether that fixes it?

**Comment by PedroMDuarte** [comment] 2016-08-11 03:48
Thanks for the reply!  Yeah I am not in a rush, for now I have kept the older version of `requests`.  Mainly reported the issue so that there was record of it in case others found it.  I will go ahead and close the ticket.

**Closed** 2016-08-11 03:49 UTC
