### ISSUE TITLE
`auth=False` in request results in HdfsError: Authentication failure.

### ISSUE THREAD

**Issue by pvarsh** [mtth/hdfs#42] opened 2016-06-01 15:24 UTC
I am using the library to work with two kerberized Hadoop clusters (Cluster A and Cluster B). The library works beautifully with Cluster A. It raises `HdfsError: Authentication failure. Check your credentials` on Cluster B.

It seems that Cluster B needs the request to the redirect location to be signed as well, but `consumer()` sets `auth=False` when it calls `_request` ([Line 394](https://github.com/mtth/hdfs/blob/master/hdfs/client.py#L394)). The request is sent in using `_session` in  `_request()` ([lines 174-180](https://github.com/mtth/hdfs/blob/master/hdfs/client.py#L174-L180)). Since `kwargs['auth'] is False`, `_session.auth` is not used. Somehow this is only a problem on Cluster B.

Adding `del kwargs['auth']` before [Line 174](https://github.com/mtth/hdfs/blob/master/hdfs/client.py#L174) patches the problem for Cluster B.

**Comment by mtth** [comment] 2016-06-01 16:49
Thanks for reporting this. I'm unable to reproduce this locally unfortunately, do you have any idea why this is happening on one cluster and not the other?

Since this looks Kerberos-specific, it would be best if we could localize the fix there. Could you try changing [this line](https://github.com/mtth/hdfs/blob/master/hdfs/ext/kerberos.py#L96) to `if not kwargs.get('auth'):` and checking against cluster B?

**Comment by pvarsh** [comment] 2016-06-01 19:35
Thanks for the quick response! I changed [the line](https://github.com/mtth/hdfs/blob/master/hdfs/ext/kerberos.py#L96) you asked, but got the same result. Unfortunately I don't know how Cluster A is different from Cluster B - I only have access to them through WebHDFS.

Is the purpose of `'auth'` in `kwargs` passed to `_request()` ([Line 89](https://github.com/mtth/hdfs/blob/master/hdfs/ext/kerberos.py#L89)) to act as a flag for delay behavior to avoid replay errors ([Lines 99-104](https://github.com/mtth/hdfs/blob/master/hdfs/ext/kerberos.py#L99-L104)), or should it be passed through to super's `_request()` method and hence `self._session.request()` call ([Line 179](https://github.com/mtth/hdfs/blob/master/hdfs/client.py#L179))?

If I understand correctly, if `'auth'` is removed from `kwargs` by ([Line 179](https://github.com/mtth/hdfs/blob/master/hdfs/client.py#L179)), the request will be signed with the `HTTPKerberosAuth` object that is set as a `session` attribute ([Line 86](https://github.com/mtth/hdfs/blob/master/hdfs/ext/kerberos.py#L86)), which is what a kerberized cluster would expect. In this way the behavior of Cluster B that is requiring every request to be signed seems normal, but somehow Cluster A is ok with redirected requests being unsigned.

Do you know if adding `del kwargs['auth']` before lines [98](https://github.com/mtth/hdfs/blob/master/hdfs/ext/kerberos.py#L98) and [105](https://github.com/mtth/hdfs/blob/master/hdfs/ext/kerberos.py#L98) OR deleting `auth=False` in [Line 394](https://github.com/mtth/hdfs/blob/master/hdfs/client.py#L394) would break anything? If not, it would solve the problem with Cluster B and default to using session's authenticator.

**Comment by mtth** [comment] 2016-06-02 17:49
> I changed the line you asked, but got the same result.

Thanks for trying it out!

> Is the purpose of 'auth' in kwargs passed to _request() (Line 89) to act as a flag for delay behavior to avoid replay errors (Lines 99-104), or should it be passed through to super's _request() method and hence self._session.request() call (Line 179)?

Both. It's passed to the base `_request` method if present. The branch is an optimization to allow for parallel uploads, if I remember correctly. The Kerberos clusters I'd encountered thus far only required authenticating the initial request so this freed us from the `max_concurrency` bound (usually `1`).

> Do you know if adding del kwargs['auth'] before line 105 OR deleting auth=False in Line 394 would break anything? If not, it would solve the problem with Cluster B and default to using session's authenticator.

Removing the explicit `auth=False` shouldn't break anything other than prevent parallel uploads. I think we should be able to do tweak concurrency handling to not have this drawback though: I just pushed a few changes into `master` to try and address this. Would you mind checking that it works for cluster B before I release it?

**Comment by pvarsh** [comment] 2016-06-02 19:35
Thanks for making the changes @mtth! It now works on both clusters.

**Comment by mtth** [comment] 2016-06-02 23:07
Thanks for checking - released as `2.0.8`!

**Closed by mtth** 2016-06-02 23:07 UTC
