### ISSUE TITLE
Upload can delete whole directories accidentally

### ISSUE THREAD

**Issue by anjackson** [mtth/hdfs#39] opened 2016-05-18 11:43 UTC
We were using the ```upload``` API call to transfer a file to an existing directory. Unfortunately, due to  [this line of code](https://github.com/mtth/hdfs/blob/master/hdfs/client.py#L524) it seems that when an error occurs during upload *the entire destination folder is deleted recursively*.

Fortunately, we only lost test data.

Can you consider disabling deletes by default, or perhaps just when the target path is a folder?

**Comment by mtth** [comment] 2016-05-18 13:53
Sorry to hear that. Would you be able to reproduce this behavior?

The current behavior uses a temporary path as destination if the original path already existed. Since it's only this temporary path that gets deleted, I'm unsure how existing files got deleted. Were you uploading other files to the destination folder during the call to `upload`?

**Comment by anjackson** [comment] 2016-05-18 20:21
What I think is happening is that the WebHDFS endpoint threw an error (due to too-many-open-files) when [the client requested the status](https://github.com/mtth/hdfs/blob/master/hdfs/client.py#L458).  Under these conditions, the client checks if the error is because it's a directory, but otherwise assumes the error means the files does not exist (and [sets the temp_path to the hdfs_path](https://github.com/mtth/hdfs/blob/master/hdfs/client.py#L465-L466)). The upload then failed, at which point the code cleaned up by recursively removing the folder.

It's awkward to test because I need to force the WebHDFS service to respond with an error the client code does not expect. I'll try to set something up.

**Comment by mtth** [comment] 2016-05-18 20:50
Thanks for the extra information. I just committed a change (3871cf6ce8fdc84a6bd38bb31e016c2ad4dd21d1) with the following improvements to `upload`:

+ A new `cleanup` option to allow disabling automatic cleanup of partial uploads when an error occurs.
+ A slightly more robust initial directory check.

Let me know if you have any concerns, otherwise I'll release it later today.

**Comment by mtth** [comment] 2016-05-19 20:34
Released in [`2.0.7`](https://github.com/mtth/hdfs/releases/tag/2.0.7).

**Closed by mtth** 2016-05-19 20:34 UTC

**Comment by anjackson** [comment] 2016-05-19 22:20
Thanks very much for dealing with so quickly. My apologies for not being able to re-test promptly.

**Comment by mtth** [comment] 2016-05-20 15:32
No problem @anjackson. Let me know if anything doesn't work as expected.
